@startuml Categorie
left to right direction
actor "Admin" as fc
rectangle Catégories {
  usecase "Ajouter categorie" as UC1
  usecase "Suprimer categorie" as UC2
  usecase "Modifier categorie" as UC3
  usecase "Consulter categorie" as UC4
  usecase "Recherche categorie" as UC5

}
fc -- UC1
fc -- UC2
fc -- UC3
fc -- UC4
fc -- UC5
@enduml
